#!/usr/bin/env bash


## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ''
		let name++
	done
}
#Same workspaces ofr all the monitors
#workspaces
bspc monitor eDP-1 -d I II III IV V

# Second monitor
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1
    # Workspaces
    
    bspc monitor HDMI-1 -d I II III IV V
    bspc monitor eDP-1 -d VI VII VIII IX X
else
    xrandr --output HDMI-1 --off
    # Remove nodes
    while bspc node @V: --kill; do
        :
    done
    while bspc node @VI: --kill; do
        :
    done
    while bspc node @VII: --kill; do
        :
    done
    while bspc node @VIII: --kill; do
        :
    done
    # Remove workspaces
    bspc desktop -r V VI VII VIII
    # Remove monitor
    bspc monitor HDMI-1 -r
fi


bspc config border_width    1
bspc config window_gap      15
bspc config border_radius   6
bspc config split_ratio     0.50

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*



## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager mpd

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspfloat &

#Falta automatizar, Esto debe iniciarse cuando se conecte un HDMI [por arreglar]
polybar -c=/home/klaus/.config/bspwm/polybar/config otramain
