Net/ThemeName "ARK-Dark"
Net/IconThemeName "Flat-Remix-Green-Dark"
Gtk/CursorThemeName "breeze_cursors"
Gtk/CursorThemeSize 24
Gtk/FontName "Noto Sans 10"
Gtk/EnableAnimations 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
