Net/ThemeName "Arc-Darker"
Net/IconThemeName "Win11-Dark"
Gtk/CursorThemeName "Fluent"
Gtk/CursorThemeSize 24
Gtk/FontName "Inter 10"
Gtk/EnableAnimations 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
