require "nvchad.mappings"
local map = function(mode, keys, fn, desc)
  vim.keymap.set(mode, keys, fn, { desc = desc, silent = true })
end
local function telescope(name, opts)
  return function()
    require("telescope.builtin")[name](opts or {})
  end
end
local function dap(name)
  return function()
    require("dap")[name]()
  end
end
map("n", ";", ":", "Entrar a comandos")
map("i", "jk", "<Esc>", "Volver a modo normal")
map({ "n", "i", "v" }, "<C-s>", "<cmd>w<cr>", "Guardar archivo")
map("v", "J", ":m '>+1<CR>gv=gv", "Mover línea abajo")
map("v", "K", ":m '<-2<CR>gv=gv", "Mover línea arriba")
map("n", "<C-d>", "<C-d>zz", "Scroll abajo centrado")
map("n", "<C-u>", "<C-u>zz", "Scroll arriba centrado")
map("v", "<", "<gv", "Reducir sangría")
map("v", ">", ">gv", "Aumentar sangría")
map("n", "<leader>ff", function()
  require("workbench.project").files()
end, "Buscar archivos del proyecto")
map("n", "<leader>fw", function()
  require("workbench.project").grep()
end, "Buscar texto en el proyecto")
map("n", "<leader>fg", function()
  require("workbench.project").word()
end, "Buscar palabra actual")
map("n", "<leader>f/", telescope "current_buffer_fuzzy_find", "Buscar en este archivo")
map("n", "<leader>fr", telescope "resume", "Reanudar búsqueda")
map("n", "<leader>fk", telescope "keymaps", "Buscar atajos")
map("n", "<leader>fd", telescope "diagnostics", "Buscar diagnósticos")
map({ "n", "x" }, "<leader>fm", function()
  require("conform").format { async = true, lsp_format = "fallback" }
end, "Formatear archivo o selección")
map("n", "<leader>cd", vim.diagnostic.open_float, "Ver diagnóstico bajo el cursor")
map("n", "<leader>cx", "<cmd>Trouble diagnostics toggle<cr>", "Panel de diagnósticos")
map("n", "[d", function()
  vim.diagnostic.jump { count = -1, float = true }
end, "Diagnóstico anterior")
map("n", "]d", function()
  vim.diagnostic.jump { count = 1, float = true }
end, "Diagnóstico siguiente")
map("n", "<leader>gv", "<cmd>DiffviewOpen<cr>", "Git: revisar cambios")
map("n", "<leader>gh", "<cmd>DiffviewFileHistory %<cr>", "Git: historial del archivo")
map("n", "<leader>gq", "<cmd>DiffviewClose<cr>", "Git: cerrar revisión")
map("n", "<leader>gp", function()
  require("gitsigns").preview_hunk()
end, "Git: vista previa del cambio")
map("n", "<leader>gb", function()
  require("gitsigns").blame_line { full = true }
end, "Git: autor de la línea")
map("n", "<leader>gs", function()
  require("gitsigns").stage_hunk()
end, "Git: preparar bloque")
map("n", "<leader>gu", function()
  require("gitsigns").undo_stage_hunk()
end, "Git: retirar bloque preparado")
map("n", "]h", function()
  require("gitsigns").nav_hunk "next"
end, "Git: cambio siguiente")
map("n", "[h", function()
  require("gitsigns").nav_hunk "prev"
end, "Git: cambio anterior")
map("n", "<F5>", dap "continue", "Depurar: iniciar / continuar")
map("n", "<F9>", dap "toggle_breakpoint", "Depurar: punto de interrupción")
map("n", "<F10>", dap "step_over", "Depurar: siguiente línea")
map("n", "<F11>", dap "step_into", "Depurar: entrar")
map("n", "<S-F11>", dap "step_out", "Depurar: salir")
map("n", "<leader>db", dap "toggle_breakpoint", "Depurar: breakpoint")
map("n", "<leader>dc", dap "continue", "Depurar: continuar")
map("n", "<leader>do", dap "step_over", "Depurar: siguiente línea")
map("n", "<leader>di", dap "step_into", "Depurar: entrar")
map("n", "<leader>dq", dap "terminate", "Depurar: terminar")
map("n", "<leader>dt", function()
  require "dap"
  require("dapui").toggle()
end, "Depurar: paneles")
map({ "n", "v" }, "<leader>de", function()
  require "dap"
  require("dapui").eval()
end, "Depurar: inspeccionar valor")
map("n", "<leader>dB", function()
  vim.ui.input({ prompt = "Condición del breakpoint: " }, function(value)
    if value and value ~= "" then
      require("dap").set_breakpoint(value)
    end
  end)
end, "Depurar: breakpoint condicional")
map("n", "<leader>rr", function()
  require("workbench.tasks").menu()
end, "Proyecto: elegir tarea")
map("n", "<leader>rf", function()
  require("workbench.tasks").run_file()
end, "Proyecto: ejecutar archivo")
map("n", "<leader>rt", function()
  require("workbench.tasks").test_file()
end, "Proyecto: probar archivo")
map("n", "<leader>rl", function()
  require("workbench.tasks").repeat_last()
end, "Proyecto: repetir tarea")
map("n", "<leader>rp", function()
  require("workbench.project").select_python()
end, "Python: elegir intérprete")
map("n", "<leader>rc", function()
  require("workbench.project").cwd()
end, "Proyecto: usar como directorio")
map("n", "<leader>qs", function()
  require("persistence").load()
end, "Sesión: recuperar proyecto")
map("n", "<leader>ql", function()
  require("persistence").load { last = true }
end, "Sesión: recuperar última")
map("n", "<leader>qS", function()
  require("persistence").select()
end, "Sesión: elegir")
map("n", "<leader>uf", "<cmd>FormatToggle<cr>", "Formato al guardar: activar / pausar")
map("n", "<leader>uh", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = 0 }, { bufnr = 0 })
end, "Código: mostrar / ocultar tipos")
map("n", "<leader>ud", function()
  vim.diagnostic.config {
    virtual_lines = not vim.diagnostic.config().virtual_lines and { current_line = true } or false,
  }
end, "Diagnóstico: expandir línea actual")
map("n", "<leader>uw", "<cmd>set wrap!<cr>", "Texto: ajustar líneas")
map("n", "<leader>pm", "<cmd>Mason<cr>", "Herramientas: instalar / revisar")
map("n", "<leader>pl", "<cmd>Lazy<cr>", "Complementos: revisar")
map("n", "<leader>ph", "<cmd>NvimHealth<cr>", "Salud de la configuración")
map("n", "<leader>?", "<cmd>NvimGuide<cr>", "Guía personal de Neovim")
